version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/test_mart    # Mount entire project directory
      - /test_mart/.venv # Exclude virtualenv from host
    working_dir: /test_mart
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  db:
    image: mysql:8.0
    hostname: db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: