"""add_indexes

Revision ID: 6d75ae6805b5
Revises: 6d8bd49cc430
Create Date: 2025-05-18 04:08:22.324122

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d75ae6805b5"
down_revision: Union[str, None] = "6d8bd49cc430"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    op.create_index(op.f("ix_sales_sale_date"), "sales", ["sale_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sales_sale_date"), table_name="sales")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    # ### end Alembic commands ###
