"""add_unique_inventory_products

Revision ID: 9520e6e83743
Revises: 506cfe3c3805
Create Date: 2025-05-16 22:21:50.985600

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9520e6e83743"
down_revision: Union[str, None] = "506cfe3c3805"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inventory", "product_id", existing_type=mysql.INTEGER(), nullable=False
    )
    op.create_unique_constraint(None, "inventory", ["product_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "inventory", type_="unique")
    op.alter_column(
        "inventory", "product_id", existing_type=mysql.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
