name: CI Pipeline

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-root
      
      - name: Run linters
        run: |
          poetry run black --check app/ tests/
          poetry run isort --check-only app/ tests/
          poetry run ruff check app/ tests/